### PR TITLE
Disallow wrapping on language name (简体中文)

### LINKED ISSUE #86: In Chinese mode, the display of the text "Simplified Chinese:" will result in an extra line.
image

I personally feel that this display effect looks a bit awkward. Shouldn't we switch it to a synonym, such as "简中" (short for "简体中文")?

### PR DESCRIPTION
**Pull request by xicri**
Closes #86

### CODE REVIEW

**Comment by xicri** [comment]
@Bill-Haku
This PR is a fix for #86. Can you help me with testing it when you have time? I could not reproduce this issue in the Japanese environment.

1. Can you check if this issue happens on [production](https://genshin-dictionary.com/zh-CN/) on your end? (Chrome, Safari)
2. Can you test if it is fixed on [the preview environment for this branch](https://genshin-dictionary-git-fix-cn-linebreak-xicri.vercel.app/)? (Chrome, Safari)

I planned to resolve this issue by using web fonts, but because I found I need a long time to implement web fonts, I created this PR as a quick fix.

**Comment by Bill-Haku** [comment]
On Safari, it looks fine:
image

But on Chrome, the problem comes out:
image

But I failed to open the preview environment on my end:
image

**Comment by xicri** [comment]
@Bill-Haku Oh, sorry, I failed to disable authentication on preview environment. I will check my config.

**Comment by xicri** [comment]
@Bill-Haku Can you try again? Now the authentication should be disabled.

**Comment by xicri** [comment]
@Bill-Haku Thanks! I will deploy this fix on production.

**Pull request merged**
